name: Build from push

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-site
        with:
          site-url: "https://www.hb.dwhswenson.net"
      - uses: ./.github/actions/store-artifacts
        with:
          site-dir: "_site"
