name: Build from PR

on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-site
        with:
          site-url: "https://staging.hb.dwhswenson.net"
          base-url: "${{ github.event.pull_request.number }}"
      - uses: ./.github/actions/store-artifacts
        with:
          site-dir: "_site"
