name: Build from PR

on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: ./.github/actions/build-site
      - uses: dwhswenson/static-site-workflow/actions/build-jekyll-site@main
        with:
          site-url: ${{ vars.STAGING_WEBSITE }}
          base-url: ${{ github.event.pull_request.number }}
      #- uses: ./.github/actions/store-artifacts
      - uses: dwhswenson/static-site-workflow/actions/store-artifacts@main
      #- uses: ./.github/actions/store-artifacts
      - uses: dwhswenson/static-site-workflow/actions/store-artifacts@main
        with:
          site-dir: "_site"
