name: My workflow
on: 
  - pull_request:
      branches:
        - master
  - schedule:
    # weekly on Sunday 0900 UTC
    - cron: "0 9 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build the site
        run: bundle exec jekyll build
      - name: Deploy via GoStatic
        id: deploy
        uses: DigitalSVN/GoStatic@v1.0
        with:
          api-token: ${{ secrets.GOSTATIC_API_TOKEN }}
          source-dir: './_site'

