name: Build from push

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: dwhswenson/static-site-workflow/actions/build-jekyll-site@main
        with:
          site-url: "https://www.hb.dwhswenson.net"
      - uses: dwhswenson/static-site-workflow/actions/store-artifacts@main
        with:
          site-dir: "_site"
