name: Cleanup staging
description: Cleanup staging environment; this occurs on PR merge or close

on:
  pull_request:
    types: [closed, merged]

jobs:
  cleanup-staging:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Install s3cmd
        run: |
          python -m pip install s3cmd
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.STAGING_ROLE }}
      - name: Delete contents of PR folder in staging bucket
        run: |
          PR_NUM=$(echo ${{ github.event.pull_request.head.ref }} | cut -d'/' -f 3)
          echo "PR=$PR_NUM"
          s3cmd del --recursive s3://${{ secrets.STAGING_BUCKET }}/$PR_NUM/

