name: Nightly build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dwhswenson/static-site-workflow/actions/build-jekyll-site@main
