name: Nightly build

on:
  pull_request:  # DEBUG
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-site
      - uses: lycheeverse/lychee-action@v2
        fail: true


