name: Build and push to s3

on: 
  push:
    branches:
      - master
  # PR only for testing
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::730335208220:role/hb-net-bucket-and-role-WorkflowRole-6LcFv4gsMqB7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build the site
        run: bundle exec jekyll build
      # TODO: linkcheck, aspell
      - name: List s3 (test)
        run: aws s3 ls s3://hb-net-testbucket-186/
      - name: Upload to S3
        run: aws s3 cp ./_site/ s3://hb-net-testbucket-186/ --recursive
