name: Upload to staging

# This workflow takes an existing artiface from the "Test Site Build"
# workflow, extracts the contents, and uploads them to the staging bucket.

# TODO: once this is done; make a copy for production.
# Change the workflow that triggers; change the bucket

on:
  workflow_run:
    workflows: ["Test Site Build"]
    types:
      - completed
  workflow_call:  # temp; remove when done

jobs:
  stage-from-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Install s3cmd
        run: |
          python -m pip install s3cmd
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          name: "site-build"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_STAGING_ROLE }}
      - name: Extract artifact and sync with s3
        run: |
          PR_NUM=$(echo ${{ github.event.workflow_run.conclusion }} | cut -d'/' -f 3)
          tar -xvf site-build.tar.gz
          s3cmd sync ./_site/ s3://${{ secrets.STAGING_BUCKET }}/$PR_NUM/
      # TODO: possible comment with link (if comment hasn't already been made?)

  cleanup-artifact:
    needs: stage-from-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: "site-build"
          token: ${{ secrets.GITHUB_TOKEN }}
